name: TNTBank
main: com.felixob.tb.TNTBank
author: Chookla
version: 1.0.0
depend: ["PlaceholderAPI"]
loadbefore: ["Factions"]
commands:
    tntbank:
        usage: /<command>
        desc: Get a Wand
        
