factionDoesntExist: "&cCould not Find your Faction. Are you in one?"
generalError: "&cUh Oh. Something Went Wrong."
noPermission: "&cYou do not have permission to do that."
notAPlayer: "&cYou are not a player. Please run the command in game"
notAnArgument: "&cYou have not provided and argument. Use Withdraw/Deposit with an amount or use Check."
noAmountProvided: "&cPlease provide an amount to withdraw or deposit."
unknownDirection: "&cThat argument doesn't exist. Use Withdraw, Deposit or Check."
noFreeSpace: "&cThere is no free space in your inventory."
withdrawMessage: "&aSuccessfully withdrew from the TNT Bank."
notEnoughTNT: "&cThere is not enough TNT in your bank to withdraw."
notEnoughTNTInv: "&cThere is not enough TNT in your inventory to deposit."
negativeTNT: "&cPlease provide an amount greater than 0."
noRadius: "&cPlease provide a radius to fill in. (Less than 32)"
smallRadius: "&cPlease provide a radius bigger than 0 blocks."
noContainers: "&cNo Containers (Dispensers/Chests) found in radius!"