factionDoesntExist: "&cCould not Find your Faction. Are you in one?"
generalError: "&cUh Oh. Something Went Wrong."
noPermission: "&cYou do not have permission to do that."
notAPlayer: "&cYou are not a player. Please run the command in game"
notAnArgument: "&cYou have not provided and argument. Use Withdraw/Deposit with an amount or use Check."
noAmountProvided: "&cPlease provide an amount to withdraw or deposit."
unknownDirection: "&cThat argument doesn't exist. Use Withdraw, Deposit or Check."
noFreeSpace: "&cThere is no free space in your inventory."
withdrawMessage: "&aSuccessfully withdrew %amount% from the TNT Bank. You now have %current_tnt%"
notEnoughTNT: "&cThere is not enough TNT in your bank to withdraw. Bank has: %current_tnt% TNT"
notEnoughTNTInv: "&cThere is not enough TNT in your inventory to deposit. You have: %current_tnt% TNT"
negativeTNT: "&cPlease provide an amount greater than 0."
noRadius: "&cPlease provide a radius to fill in. (Less than 32)"
smallRadius: "&cPlease provide a radius bigger than 0 blocks."
noContainers: "&cNo Containers (Dispensers/Chests) found in radius!"
noTNT: "&cYou don't have any TNT."
stick: "&aSuccessfully gave you a TNTBank Wand."
currentTNT: "&aBank now has %current_tnt% TNT."
successFill: "&aSuccessfully Filled Containers with %filled_slots% TNT."
depositMessage: "&a%amount% TNT Deposited"
tntLimit: 2000000
tntLimitReached: "You have reached the limit of %tnt_limit% TNT in the bank."
stickName: "&5TNT WAND"
stickNoTNT: "&cNo TNT in that Container."